database:
  host: "postgres"
  port: 5432
  dbname: oilpalm
  connections: 100

log_level: INFO

otel:
  endpoint:
    http: "http://localhost:4318"
    grpc: "http://localhost:4317"

service_name: payment-link
